hoppa/apps/dashboards/urls.py
from django.conf.urls import url
from .views import GeneralDashboardView, CountyDashboardView, FarmerDashboardView, dashboard_selector


urlpatterns = [
    url(r'^$', dashboard_selector, name="dashboard-selector"),
    url(r'^general/$', GeneralDashboardView.as_view(), name="general-dashboard"),
    url(r'^county/$', CountyDashboardView.as_view(), name="county-dashboard"),
    url(r'^farmer/$', FarmerDashboardView.as_view(), name="farmer-dashboard")
]

hoppa/apps/ponds/urls.py
from django.conf.urls import url
from .views import PondListView


urlpatterns = [
    url(r'^$', PondListView.as_view(), name="list-ponds"),
    # url(r'pond/add/$', PondCreateView.as_view(), name='pond-add'),
    # url(r'pond/(?P<pk>[0-9]+)/$', PondUpdateView.as_view(), name='pond-update'),
    # url(r'pond/(?P<pk>[0-9]+)/delete/$', PondDeleteView.as_view(), name='pond-delete'),
]

hoppa/apps/profiles/urls.py
from django.conf.urls import url
from .views import UserListView, user_login, CreateUserView, UpdateUserView, DeleteUserView, FarmerCreateView, \
    FarmerUpdateView, FarmerDeleteView, FarmerListView, CountyRepsListView, FarmerDetailView, UserDetailView, CountyFarmerListView
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^$', UserListView.as_view(), name="list-users"),
    url(r'^login/$', user_login, name="login"),
    url(r'^logout/$', logout, {'next_page': '/profile/login'}, name='logout'),
    url(r'^user/new/$', CreateUserView.as_view(), name="create-user"),
    url(r'^user/(?P<pk>\d+)/$', UpdateUserView.as_view(), name="update-user"),
    url(r'^user/(?P<pk>\d+)/details/$', UserDetailView.as_view(), name="user-details"),
    url(r'^user/delete/(?P<pk>\d+)/$', DeleteUserView.as_view(), name="delete-user"),
    url(r'^farmers/$', FarmerListView.as_view(), name="list-farmers"),
    url(r'^farmers/county/$', CountyFarmerListView.as_view(), name="list-county-farmers"),
    url(r'^county-reps/$', CountyRepsListView.as_view(), name="list-county-reps"),
    url(r'^farmer/new/$', FarmerCreateView.as_view(), name="create-farmer"),
    url(r'^farmer/(?P<pk>\d+)/$', FarmerUpdateView.as_view(), name="update-farmer"),
    url(r'^farmer/(?P<pk>\d+)/details/$', FarmerDetailView.as_view(), name="farmer-details"),
    url(r'^farmer/delete/(?P<pk>\d+)/$', FarmerDeleteView.as_view(), name="delete-farmer"),
]

hoppa/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from hoppa.views import HomepageView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomepageView.as_view(template_name='index.html'), name='home'),
    url(r'^profile/', include('profiles.urls')),
    url(r'^questionnaire/', include('questionnaires.urls')),
    url(r'^pond/', include('ponds.urls')),
    url(r'^dashboard/', include('dashboards.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hoppa/apps/ponds/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Pond(models.Model):
    owner = models.ForeignKey(User)

    def __str__(self):
        return self.owner.username

    def get_absolute_url(self):
        return reverse('pond-detail', kwargs={'pk': self.pk})

hoppa/apps/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from rolepermissions.roles import assign_role


ROLE_CHOICES = (
    ('General Admin', 'General Admin'),
    ('County Admin', 'County Admin'),
    ('Farmer', 'Farmer')
)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_account")
    profile_picture = models.FileField(upload_to='profile_photos/%Y/%m/%d/')
    location = models.CharField(max_length=200)
    role = models.CharField(choices=ROLE_CHOICES, max_length=30)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="user_admin")

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('update-user', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super(UserProfile, self).save(*args, **kwargs)
        if self.role == 'General Admin':
            assign_role(self.user, 'general_admin')
        elif self.role == 'County Admin':
            assign_role(self.user, 'county_admin')
        else:
            assign_role(self.user, 'farmer')

hoppa/apps/dashboards/views.py
from django.http.response import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView
from rolepermissions.checkers import has_permission
from rolepermissions.mixins import HasRoleMixin


class GeneralDashboardView(HasRoleMixin, TemplateView):

    template_name = "dashboards/general.html"
    allowed_roles = "general_admin"

    def get_context_data(self, **kwargs):
        context = super(GeneralDashboardView, self).get_context_data(**kwargs)
        context['profile'] = self.request.user
        return context


class CountyDashboardView(HasRoleMixin, TemplateView):

    template_name = "dashboards/county.html"
    allowed_roles = "county_admin"

    def get_context_data(self, **kwargs):
        context = super(CountyDashboardView, self).get_context_data(**kwargs)
        context['profile'] = self.request.user
        return context


class FarmerDashboardView(HasRoleMixin, TemplateView):

    template_name = "dashboards/farmer.html"
    allowed_roles = "farmer"

    def get_context_data(self, **kwargs):
        context = super(FarmerDashboardView, self).get_context_data(**kwargs)
        context['profile'] = self.request.user
        return context


def dashboard_selector(request):
    if request.user.is_authenticated():
        # Is the account active? It could have been disabled.
        if request.user.is_active:
            if has_permission(request.user, 'general_dashboard'):
                return HttpResponseRedirect(reverse('general-dashboard'))
            elif has_permission(request.user, 'county_dashboard'):
                return HttpResponseRedirect(reverse('county-dashboard'))
            else:
                return HttpResponseRedirect(reverse('farmer-dashboard'))
        else:
            # An inactive account was used - no logging in!
            return HttpResponse("Your account is disabled.")
    else:
        return render(request, 'profiles/login.html')

hoppa/apps/ponds/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.utils import timezone
from hoppa.apps.ponds.models import Pond
from rolepermissions.mixins import HasRoleMixin


class PondListView(HasRoleMixin, ListView):

    model = Pond
    template_name = "ponds/list.html"
    allowed_roles = "general_admin"

    def get_context_data(self, **kwargs):
        context = super(PondListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class PondCreateView(CreateView):
    model = Pond
    fields = ['owner']


class PondUpdateView(UpdateView):
    model = Pond
    fields = ['owner']


class PondDeleteView(DeleteView):
    model = Pond
    success_url = reverse_lazy('list-ponds')

hoppa/apps/profiles/views.py
from django.contrib.auth import authenticate, login
from django.http.response import HttpResponseRedirect, HttpResponse, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.utils import timezone
from rolepermissions.mixins import HasRoleMixin
from rolepermissions.checkers import has_permission
from extra_views import CreateWithInlinesView, UpdateWithInlinesView, InlineFormSet
from django.contrib.auth.models import User
from hoppa.apps.profiles.models import UserProfile
from hoppa.apps.profiles.forms import UserProfileInline as FarmerProfileInline, CustomUserChangeForm, GeneralUserProfileInline
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from hoppa.apps.questionnaires.models import Questionnaire


class UserListView(HasRoleMixin, ListView):

    model = User
    template_name = "profiles/list.html"
    allowed_roles = "general_admin"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['profile'] = self.request.user
        return context


class FarmerListView(HasRoleMixin, ListView):

    model = User
    template_name = "farmers/list.html"
    allowed_roles = "general_admin"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(FarmerListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['profile'] = self.request.user
        return context

    def get_queryset(self):
        queryset = User.objects.filter(user_account__role='Farmer')
        return queryset


class CountyFarmerListView(HasRoleMixin, ListView):

    model = User
    template_name = "farmers/list.html"
    allowed_roles = "county_admin"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(CountyFarmerListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['profile'] = self.request.user
        return context

    def get_queryset(self):
        queryset = User.objects.filter(user_account__role="Farmer", user_account__admin=self.request.user)
        return queryset


class CountyRepsListView(HasRoleMixin, ListView):

    model = User
    template_name = "county_reps/list.html"
    allowed_roles = "general_admin"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(CountyRepsListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['profile'] = self.request.user
        return context

    def get_queryset(self):
        queryset = User.objects.filter(user_account__role='County Admin')
        return queryset


def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # We'll send the user back to his relevant dashboard based on permissions.
                login(request, user)
                if has_permission(user, 'general_dashboard'):
                    return HttpResponseRedirect(reverse('general-dashboard'))
                elif has_permission(user, 'county_dashboard'):
                    return HttpResponseRedirect(reverse('county-dashboard'))
                else:
                    return HttpResponseRedirect(reverse('farmer-dashboard'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'profiles/login.html')

#
# class CreateUserView(HasRoleMixin, CreateWithInlinesView):
#     model = User
#     inlines = [UserProfileInline]
#     form_class = UserCreationForm
#     template_name = "profiles/create.html"
#     allowed_roles = "general_admin"
#
#     def get_context_data(self, **kwargs):
#         context = super(CreateUserView, self).get_context_data(**kwargs)
#         context['now'] = timezone.now()
#         context['profile'] = self.request.user
#         return context
#
#     def get_success_url(self):
#         return reverse('update-user', args=(self.object.id,))


class CreateUserView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "profiles/create.html"
    http_method_names = ["POST", "GET"]

    def get_context_data(self, **kwargs):
        context = super(CreateUserView, self).get_context_data(**kwargs)
        context['inline'] = GeneralUserProfileInline
        context['profile'] = self.request.user
        return context

    def dispatch(self, request, *args, **kwargs):
        handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
        if has_permission(self.request.user, 'manage_county_admin'):
            pass
        else:
            return HttpResponseForbidden()
        self.request = request
        self.args = args
        self.kwargs = kwargs
        return handler(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = GeneralUserProfileInline(request.POST, request.FILES)
        form_valid = form.is_valid()
        formset_valid = formset.is_valid()

        if form_valid and formset_valid:
            self.object = form.save()
            profile = formset.save(commit=False)
            profile.user = self.object
            profile.admin = request.user
            profile.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse('update-user', args=(self.object.id,))


# class UpdateUserView(HasRoleMixin, UpdateWithInlinesView):
#     model = User
#     inlines = [UserProfileInline]
#     form_class = UserChangeForm
#     template_name = "profiles/update.html"
#     allowed_roles = "general_admin"
#
#     def get_context_data(self, **kwargs):
#         context = super(UpdateUserView, self).get_context_data(**kwargs)
#         context['now'] = timezone.now()
#         context['profile'] = self.request.user
#         return context
#
#     def get_success_url(self):
#         return reverse('update-user', args=(self.object.id,))


class UpdateUserView(UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = "profiles/update.html"
    http_method_names = ["POST", "GET"]

    def get_context_data(self, **kwargs):
        context = super(UpdateUserView, self).get_context_data(**kwargs)
        context['profile'] = self.request.user
        if self.request.POST:
            context['inline'] = GeneralUserProfileInline(self.request.POST, instance=self.object.user_account)
        else:
            context['inline'] = GeneralUserProfileInline(instance=self.object.user_account)
        return context

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        inline = GeneralUserProfileInline(instance=self.object.user_account)
        return self.render_to_response(self.get_context_data(form=form, inline=inline))

    def dispatch(self, request, *args, **kwargs):
        handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
        if has_permission(self.request.user, 'manage_county_admin'):
            pass
        else:
            return HttpResponseForbidden()
        self.request = request
        self.args = args
        self.kwargs = kwargs
        return handler(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        request.POST = request.POST.copy()
        request.POST['admin'] = request.user

        return super(UpdateUserView, self).post(request, **kwargs)

    def get_success_url(self):
        return reverse('update-user', args=(self.object.id,))


class DeleteUserView(HasRoleMixin, DeleteView):
    model = User
    allowed_roles = "general_admin"
    template_name = "profiles/delete.html"

    def get_success_url(self):
        return reverse('list-users', args=(self.object.id,))


class FarmerCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "farmers/create.html"
    http_method_names = ["POST", "GET"]

    def get_context_data(self, **kwargs):
        context = super(FarmerCreateView, self).get_context_data(**kwargs)
        context['inline'] = FarmerProfileInline
        context['profile'] = self.request.user
        return context

    def dispatch(self, request, *args, **kwargs):
        handler = getattr(self, request.method.lower(), self.http_method_not_allowed)
        if has_permission(self.request.user, 'manage_farmer'):
            pass
        else:
            return HttpResponseForbidden()
        self.request = request
        self.args = args
        self.kwargs = kwargs
        return handler(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        copy = self.request.POST.copy()
        copy.update({'role': 'Farmer'})
        formset = FarmerProfileInline(copy, request.FILES)
        form_valid = form.is_valid()
        formset_valid = formset.is_valid()

hoppa/views.py
from django.views.generic.base import TemplateView


class HomepageView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super(HomepageView, self).get_context_data(**kwargs)
        context['profile'] = self.request.user
        return context

hoppa/templates/profiles/create.html
{% extends 'base.html' %}

{% block title %} Update User {% endblock %}

{% block content %}

<ul class="breadcrumb">
                    <li><a href="#">Pages</a></li>
                    <li class="active">Add User</li>
                </ul>
                <!-- END BREADCRUMB -->

                <!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">

                    <div class="row">
                        <div class="col-md-12">

                            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="{% url 'create-user' %}">{% csrf_token %}
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"><strong>New</strong> User</h3>
                                    <ul class="panel-controls">
                                        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                                    </ul>
                                </div>

                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Username</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                <input type="text" name="username" autofocus required id=id_username" class="form-control"/>
                                            </div>
                                            <span class="help-block">This is sample of text field</span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Password</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-unlock-alt"></span></span>
                                                <input type="password" name="password1" autofocus required id=id_password1"  class="form-control"/>
                                            </div>
                                            <span class="help-block">Enter Password</span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Password</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-unlock-alt"></span></span>
                                                <input type="password" name="password2" autofocus required id=id_password2"  class="form-control" />
                                            </div>
                                            <span class="help-block">Repeat password</span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Profile Picture</label>
                                        <div class="col-md-6 col-xs-12">
                                            <input type="file" class="fileinput" name="profile_picture" id="id_profile_picture" title="Browse file" style="left: -206.75px; top: 5px;"/>
                                            <span class="help-block">Input type photo</span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Location</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                <input type="text" name="location" autofocus required id=id_location" class="form-control"/>
                                            </div>
                                            <span class="help-block">Farmer's location</span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Role</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ inline.role }}
                                            </div>
                                            <span class="help-block">User's role</span>
                                        </div>
                                    </div>

                                </div>
                                <div class="panel-footer">
                                    <button class="btn btn-default">Clear Form</button>
                                    <button type="submit" class="btn btn-primary pull-right">Submit</button>
                                </div>
                            </div>
                            </form>

                        </div>
                    </div>

                </div>
                <!-- END PAGE CONTENT WRAPPER -->
            </div>
            <!-- END PAGE CONTENT -->

{% endblock %}

hoppa/templates/profiles/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete User</title>
</head>
<body>
<form method="post" enctype="multipart/form-data" action="{% url 'update-user' object.id %}">
{% csrf_token %}
{{ form }}
    <input type="submit" value="Delete">
</form>
</body>
</html>

hoppa/templates/profiles/list.html
{% extends 'base.html' %}

{% block title %} All Users {% endblock %}

{% block content %}
<!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li><a href="#">Pages</a></li>
                    <li class="active">All Users</li>
                </ul>
                <!-- END BREADCRUMB -->

                <!-- PAGE TITLE -->
                <div class="page-title">
                    <h2><span class="fa fa-users"></span> Users <small>{{ object_list.count }} contacts</small></h2>
                </div>
                <!-- END PAGE TITLE -->

                <!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">

                    <div class="row">
                        <div class="col-md-12">

                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <p>Use search to find contacts. You can search by: name, email, phone. Or use the advanced search.</p>
                                    <form class="form-horizontal">
                                        <div class="form-group">
                                            <div class="col-md-8">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <span class="fa fa-search"></span>
                                                    </div>
                                                    <input type="text" class="form-control" placeholder="Who are you looking for?"/>
                                                    <div class="input-group-btn">
                                                        <button class="btn btn-primary">Search</button>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <a class="btn btn-success btn-block" href="{% url 'create-user' %}"><span class="fa fa-plus"></span> Add new user</a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="row">
                        {% for object in object_list %}
                        <div class="col-md-3">
                            <!-- CONTACT ITEM -->
                            <div class="panel panel-default">
                                <div class="panel-body profile">
                                    <a href="{% url 'user-details' object.pk %}">
                                        <div class="profile-image">
                                            <img src="/media/{{ object.user_account.profile_picture }}" alt="{{ object.username }}"/>
                                        </div>
                                    </a>
                                    <div class="profile-data">
                                        <div class="profile-data-name">{{ object.username }}</div>
                                        <div class="profile-data-title">{{ object.user_account.role }}</div>
                                    </div>
                                    <div class="profile-controls">
                                        <a href="#" class="profile-control-left"><span class="fa fa-info"></span></a>
                                        <a href="#" class="profile-control-right"><span class="fa fa-phone"></span></a>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <div class="contact-info">
                                        <p><small>First Name</small><br/>{{ object.first_name }}</p>
                                        <p><small>Last Name</small><br/>{{ object.last_name }}</p>
                                        <p><small>Mobile</small><br/>{{ object.mobile_number }}</p>
                                        <p><small>Email</small><br/>{{ object.email }}</p>
                                        <p><small>Address</small><br/>{{ object.user_account.location }}</p>
                                    </div>
                                </div>
                            </div>
                            <!-- END CONTACT ITEM -->
                        </div>
                        {% endfor %}
                        </div>
                    </div>
                     {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="pagination pagination-sm pull-right push-down-10 push-up-10">
                                {% if page_obj.has_previous %}
                                    <span><a href="/profile/farmers?page={{ page_obj.previous_page_number }}">PREVIOUS</a></span>
                                {% endif %}
                                <li>
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </li>
                                {% if page_obj.has_next %}
                                    <span><a href="/profile?page={{ page_obj.next_page_number }}">NEXT</a></span>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    {% endif %}

                </div>
                <!-- END PAGE CONTENT WRAPPER -->
            </div>
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->
{% endblock %}